### ISSUE TITLE
Anything else needed to run?

### ISSUE THREAD

**Issue by DominikVogel** [ndi-ct/uptime-kuma#1]
Thanks for the compose file. I was able to start the containers and set-up Uptime Kuma. However, it does not seem to work correctly. When I set up a monitor for ct.de I get the following error: `getaddrinfo EAI_AGAIN ct.de`. It seems like outgoing traffic is blocked. I also do not get a Let's Encrypt certificate for the Uptime Kuma installation.

Is there anything else needed to set everything up besides adding an email address and a domain to `docker-compose.yml` and running `docker-compose up -d`?

Thanks!

**Comment by ndi-ct** [comment]
Hey Dominik,

* what kind of monitor are you using to look up ct.de? For the standard-HTTP(S)-monitor, you have to enter a valid, complete URL (https://ct.de).

* are you using Traefik + Uptime Kuma on your local network (e.g. at home) or on a VPS with a fixed IPv4-Adress? For Traefik,  port 80 (for Let's Encrypt) and port 443 (for the reverse-proxy) need to be open. 

Best regards,
Niklas

**Comment by DominikVogel** [comment]
Hi Niklas,

thanks a lot for your answer!

- I used a standard-HTTP(S)-monitor and added the full URL (see image).

![grafik](https://user-images.githubusercontent.com/12719863/148083762-88104051-732c-4a4b-a676-1de21986c24d.png)

- I am using a VPS (provided by delta-networks.de) that seems to have a fixed IPv4. Do I need to open the ports in Iptables or somewhere else?

**Comment by ndi-ct** [comment]
This error doesn't seem to be related to uptike-kuma, but rather the DNS-configuration of your VPS-provider. Maybe take a look at [Issue #114](https://github.com/louislam/uptime-kuma/issues/114) in the uptime-kuma-repository for reference.

**Comment by DominikVogel** [comment]
Thanks a lot! I found a solution in one of the linked issues (https://github.com/louislam/uptime-kuma/issues/295#issuecomment-910144773) 

It helps to manually define a DNS resolver in the uptime-kuma part of `docker-compose.yml`:

```yaml
  dns:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
```

**Comment by Edgarruiz856** [comment]
edgarplasticos3@hotmail.com

**Comment by Edgarruiz856** [comment]
- [x]     edgarplasticos3@hotmail.com> Hey Dominik,
> 
> * what kind of monitor are you using to look up ct.de? For the standard-HTTP(S)-monitor, you have to enter a valid, complete URL (https://ct.de).
> 
> * are you using Traefik + Uptime Kuma on your local network (e.g. at home) or on a VPS with a fixed IPv4-Adress? For Traefik,  port 80 (for Let's Encrypt) and port 443 (for the reverse-proxy) need to be open. 
> 
> Best regards,
> Niklas
